[run]
working_dir      = "."
gas              = "He"
memory_total_gib = 10

[field_cache]
mode = "auto"

[grid]
t_min        = -200.0
t_max        =  200.0
dt           =  0.02
spatial_axes = "z"
fixed.x      = 0.0
fixed.y      = 0.0
ax1_min      = -10.0
ax1_max      =  10.0
dx1          =  0.05

[[laser]]
E0              = 100.0
wavelength      = 1.0
phase0          = 0.0
k_vec           = [0.0, 0.0, 1.0]
r_start         = [0.0, 0.0, 0.0]
temporal_type   = "gaussian"
tau             = 30.0
transverse_type = "gaussian"
w0              = 4.0
zf              = 0.0
polarization    = "linear"
angle           = 0.0

[[laser]]
E0              = 100.0
wavelength      = 0.8
phase0          = 0.0
k_vec           = [0.0, 0.0, 1.0]
r_start         = [0.0, 0.0, 0.0]
temporal_type   = "gaussian"
tau             = 25.0
transverse_type = "gaussian"
w0              = 12.0
zf              = 0.0
polarization    = "circular"
angle           = 0.0
sense           = "left"

[[field_diag]]
axes       = "tz"
components = ["Ex", "Ey"]

[[field_diag]]
axes       = "t"
components = ["Ex", "Ey"]
pos_z      = 0

[ionization_frac]

[[phase_space]]
phase_space = "pxpy"
bins1.nbins =  500
bins1.min   = -0.065
bins1.max   =  0.065
bins2.nbins =  500
bins2.min   = -0.065
bins2.max   =  0.065
region.zmin = -2.0
region.zmax =  2.0


[[particles]]
ppc         = 50
seed        = 1234
sampling.nz = 256
