# =========================
# 0) General run parameters
# =========================

[run]
working_dir = "."
gas = "He"

# =========================
# 1) Field cache parameters
# =========================

[field_cache]
mode = "auto" # "auto" | "compute" | "load" | "off"
write = true  # if computing: write HDF5 outputs

# ==============================
# 2) Temporal/Spatial parameters
# ==============================

[grid]
t_min = -200.0
t_max = 200.0
dt = 0.02

# 1D: "x","y","z" ; 2D: "xy","xz","yz" (and permutations)
spatial_axes = "zx"

fixed = { x = 0.0, y = 0.0, z = 0.0 }

# Axis definitions:
# ax1 corresponds to first letter in spatial_axes, ax2 to second letter (if present)
ax1_min = -0.5
ax1_max = 0.5
dx1 = 0.02

ax2_min = -0.5
ax2_max = 0.5
dx2 = 0.02
# For 1D, omit ax2_*.

# =========================
# 3) Lasers (>=1 required)
# =========================

[[laser]]
type = "standard"
E0 = 200.0
wavelength = 0.8
phase0 = 0.0
k_vec = [0.0, 0.0, 1.0]
r_start = [0.0, 0.0, 0.0]
use_retarded_time = true
temporal_type = "gaussian"
tau = 30.0
transverse_type = "gaussian"
w0 = 4.0
zf = 0.0
polarization = "linear"      # "linear" | "circular" | "Jones"
angle = 0.0

# ====================
# 4) Field diagnostics
# ====================

[[field_diag]]
components = ["Ex", "Ey"]
axes = "tz"
pos_x = 0.10
pos_y = 0.0
pos_z = 0.0
pos_t = 0

[[field_diag]]
components = ["Ex", "Ey"]
axes = "t"
pos_x = 0
pos_y = 0.0
pos_z = 0
pos_t = 10.0

# =========================
# 5) Ionization diagnostics
# =========================

[ionization_frac]

# =========================
# 6) Phase-space diagnostic
# =========================

[[phase_space]]

phase_space = "pz" # "px", "py", "pz", "pxpy", "pxpz", "pypz" (order matters)
#region = { xmin = -5, xmax = 5, zmin = -5, zmax = 5 } # Spatial region (if it is over the cache bounds, goes to the edge of the cache) and ignores the coordinate not in the simulation. This is optional, if omitted defaults to entire cache region.
envelope_cut = 1e-6                            # ignore points where envelope is below threshold
bins1 = { nbins = 600, min = -2.0, max = 2.0 }
# bins2 = { nbins=600, min=-2.0, max=2.0 }                    # only for 2D phase space

[[phase_space]]

phase_space = "pxpy"                                                      # "px", "py", "pz", "pxpy", "pxpz", "pypz" (order matters)
region = { xmin = -5, xmax = 5, ymin = 0, ymax = 1, zmin = -5, zmax = 5 } # Spatial region (if it is over the cache bounds, goes to the edge of the cache) and ignores the coordinate not in the simulation. This is optional, if omitted defaults to entire cache region.
envelope_cut = 1e-6                                                       # ignore points where envelope is below threshold
bins1 = { nbins = 600, min = -2.0, max = 2.0 }
bins2 = { nbins = 600, min = -2.0, max = 2.0 }                            # only for 2D phase space
